export const FETCH_REUSE = 'FETCH_REUSE';
export const FETCH_METRICS = 'FETCH_METRICS';
export const FETCH_COMM = 'FETCH_COMM';
export const FETCH_TIMELINE = 'FETCH_TIMELINE';
export const FETCH_CCT = 'FETCH_CCT';
export const FETCH_EXPERIMENTS = 'FETCH_EXPERIMENTS';
