#include "./kernels/version_0.cuh"
#include "./kernels/version_1.cuh"
// #include "./kernels/kernel2.cuh"
// #include "./kernels/kernel3.cuh"
// #include "./kernels/kernel4.cuh"
// #include "./kernels/kernel5.cuh"
// #include "./kernels/kernel6.cuh"
// #include "./kernels/kernel7.cuh"
// #include "./kernels/kernel8.cuh"