#include "./kernels/version_0.cuh"
#include "./kernels/version_1.cuh"
#include "./kernels/version_2.cuh"
#include "./kernels/version_3.cuh"
#include "./kernels/version_4.cuh"
#include "./kernels/version_5.cuh"
// #include "./kernels/kernel6.cuh"
// #include "./kernels/kernel7.cuh"
// #include "./kernels/kernel8.cuh"
